apiVersion: v1
kind: Secret
metadata:
  name: connectsphere-secrets
  namespace: connectsphere
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgre"     # ← changed
  CLOUDINARY_CLOUD_NAME: "dvdhpvwaq"
  CLOUDINARY_API_KEY: "251374278598845"
  CLOUDINARY_API_SECRET: "ULHNtzz5kOHG6c752ODOlUyY27k"
  MAIL_USERNAME: "kushagrabvbpn0879@gmail.com"
  MAIL_PASSWORD: "xwnponjndyohqfzx"