apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: connectsphere
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: connectsphere
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5433
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: connectsphere-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: connectsphere-secrets
                  key: POSTGRES_PASSWORD
            - name: PGPORT
              value: "5433"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-p", "5433"]    # ← changed
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: init-script
          configMap:
            name: postgres-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: connectsphere
spec:
  selector:
    app: postgres
  ports:
    - port: 5433
      targetPort: 5433
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: connectsphere
data:
  init-db.sh: |
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "postgres" <<-EOSQL
        SELECT 'CREATE DATABASE auth_db' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'auth_db')\gexec
        SELECT 'CREATE DATABASE user_db' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'user_db')\gexec
        SELECT 'CREATE DATABASE post_db' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'post_db')\gexec
        SELECT 'CREATE DATABASE connection_db' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'connection_db')\gexec
        SELECT 'CREATE DATABASE messaging_db' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'messaging_db')\gexec
        SELECT 'CREATE DATABASE notification_db' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'notification_db')\gexec
        SELECT 'CREATE DATABASE job_db' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'job_db')\gexec
    EOSQL