apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: connectsphere
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 3; done']
        - name: wait-for-eureka
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z eureka-server 8761; do echo waiting for eureka; sleep 3; done']
      containers:
        - name: auth-service
          image: connectsphere/auth-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/auth_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: connectsphere-config
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: connectsphere-secrets
                  key: POSTGRES_PASSWORD
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: connectsphere-config
                  key: EUREKA_URL
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: connectsphere-config
                  key: JWT_SECRET
            - name: JWT_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  name: connectsphere-config
                  key: JWT_EXPIRATION
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "384Mi"
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: connectsphere
spec:
  selector:
    app: auth-service
  ports:
    - port: 8081
      targetPort: 8081