apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: connectsphere
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 3; done']
        - name: wait-for-eureka
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z eureka-server 8761; do echo waiting for eureka; sleep 3; done']
      containers:
        - name: user-service
          image: connectsphere/user-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/user_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: connectsphere-config
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: connectsphere-secrets
                  key: POSTGRES_PASSWORD
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: connectsphere-config
                  key: EUREKA_URL
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: connectsphere-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: connectsphere-secrets
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: connectsphere-secrets
                  key: CLOUDINARY_API_SECRET
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "384Mi"
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: connectsphere
spec:
  selector:
    app: user-service
  ports:
    - port: 8082
      targetPort: 8082